name: Linting

on: [push, workflow_dispatch]

jobs:
  # Linting (JS Standard)
  lint-standard:
    name: Lint - JS Standard
    # Using ubuntu because it's stable
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: yarn add standard

      - name: Lint project
        run: npx standard

  # Linting (shellcheck)
  lint-shellcheck:
    name: Lint - Shellcheck
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        env:
          SHELLCHECK_OPTS: -e SC3045 -e SC2162

  # Linting (Checkov)
  lint-checkov:
    name: Lint - Checkov
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Lint project
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .

  # Linting (Markdownlint)
  lint-markdownlint:
    name: Lint - Markdownlint
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: markdownlint-cli
        uses: nosborn/github-action-markdown-cli@v3.0.1
        with:
          files: .
          config_file: .markdownlint.yaml
